#!/usr/bin/env bash

#Fixs a container so that Nginx is running as the nginx user.

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

#ensures nginx is listening to port 8080 in sites-available confi
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
#give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

#start nginx
sudo -u nginx service nginx start
